### ISSUE TITLE
Relay access denied error when adding new user.

### ISSUE THREAD

**Issue by wholewheattoast** [gcarothers/threethings#11]
When running command like
`3things add-user jdoe@example.com "J Doe"`

Following exception occurs.  User appears to be correctly inserted into db.

```
(threethings) shawn@shawn-lex15.local ~/source/threethings> 3things add-user lpark@lexmachina.com "Leo Park"
DEBUG:txn.140735180435456:new transaction
DEBUG:txn.140735180435456:commit <repoze.sendmail.delivery.MailDataManager object at 0x101da4d10>
DEBUG:txn.140735180435456:commit <zope.sqlalchemy.datamanager.SessionDataManager object at 0x101d97d90>
CRITICAL:txn.140735180435456:A storage error occurred during the second phase of the two-phase commit.  Resources may be in an inconsistent state.
ERROR:txn.140735180435456:Error in tpc_abort() on manager <zope.sqlalchemy.datamanager.SessionDataManager object at 0x101d97d90>
Traceback (most recent call last):
  File "/Users/shawn/.virtualenvs/threethings/lib/python2.7/site-packages/transaction/_transaction.py", line 432, in _cleanup
    rm.tpc_abort(self)
  File "/Users/shawn/.virtualenvs/threethings/lib/python2.7/site-packages/zope/sqlalchemy/datamanager.py", line 110, in tpc_abort
    assert self.state is not 'committed'
AssertionError
DEBUG:txn.140735180435456:abort
Traceback (most recent call last):
  File "/Users/shawn/.virtualenvs/threethings/bin/3things", line 9, in <module>
    load_entry_point('threethings==0.1.0', 'console_scripts', '3things')()
  File "/Users/shawn/source/threethings/threethings/cli.py", line 223, in main
    parser.dispatch()
  File "/Users/shawn/.virtualenvs/threethings/lib/python2.7/site-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/Users/shawn/.virtualenvs/threethings/lib/python2.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/Users/shawn/.virtualenvs/threethings/lib/python2.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/Users/shawn/.virtualenvs/threethings/lib/python2.7/site-packages/argh/dispatching.py", line 265, in _call
    for line in result:
  File "/Users/shawn/source/threethings/threethings/cli.py", line 138, in add_user
    transaction.commit()
  File "/Users/shawn/.virtualenvs/threethings/lib/python2.7/site-packages/transaction/_manager.py", line 111, in commit
    return self.get().commit()
  File "/Users/shawn/.virtualenvs/threethings/lib/python2.7/site-packages/transaction/_transaction.py", line 280, in commit
    reraise(t, v, tb)
  File "/Users/shawn/.virtualenvs/threethings/lib/python2.7/site-packages/transaction/_transaction.py", line 271, in commit
    self._commitResources()
  File "/Users/shawn/.virtualenvs/threethings/lib/python2.7/site-packages/transaction/_transaction.py", line 417, in _commitResources
    reraise(t, v, tb)
  File "/Users/shawn/.virtualenvs/threethings/lib/python2.7/site-packages/transaction/_transaction.py", line 399, in _commitResources
    rm.tpc_finish(self)
  File "/Users/shawn/.virtualenvs/threethings/lib/python2.7/site-packages/repoze/sendmail/delivery.py", line 71, in tpc_finish
    self.callable(*self.args)
  File "/Users/shawn/.virtualenvs/threethings/lib/python2.7/site-packages/repoze/sendmail/mailer.py", line 99, in send
    connection.sendmail(fromaddr, toaddrs, message)
  File "/usr/local/Cellar/python/2.7.5/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 734, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'lpark@lexmachina.com': (454, '4.7.1 <lpark@lexmachina.com>: Relay access denied')}
```

**Comment by wholewheattoast** [comment]
Think this was due to mandrill shut off.  closing for now.
